import { Person } from "./types";

export const SEED_PEOPLE: Person[] = [
  {
    id: "p-001",
    name: "Aïda Muluneh",
    role: "Photographer, curator",
    company: "Addis Foto Fest",
    met: "Printed Matter Art Book Fair",
    metCity: "NYC",
    captured: "2026-04-12",
    tags: ["close"],
    enriched: true,
    email: "aida@addisfotofest.org",
    phone: null,
    web: "addisfotofest.org",
    twitter: null,
    linkedin: "in/aidamuluneh",
    notes: "We talked for forty minutes about why Black print culture archives keep getting digitized and then abandoned. She invited me to visit the next print residency in Addis; I said yes before I'd checked the calendar. Bring the Nigerian magazine I promised.",
    followups: ["Send the Nsukka magazine scan", "Intro to Kiyan re: residency slot"],
    meetings: [
      {
        id: "m-001-1",
        date: "2026-04-12",
        location: "Printed Matter Art Book Fair · NYC",
        notes: "We talked for forty minutes about why Black print culture archives keep getting digitized and then abandoned. She invited me to visit the next print residency in Addis; I said yes before I'd checked the calendar. Bring the Nigerian magazine I promised.",
      },
    ],
  },
  {
    id: "p-002",
    name: "Jonas Bergström",
    role: "Type designer",
    company: "Letter Foundry",
    met: "TypeMedia studio visit",
    metCity: "The Hague",
    captured: "2026-04-09",
    tags: ["networking"],
    enriched: true,
    email: "jonas@letterfoundry.nl",
    phone: null,
    web: "letterfoundry.nl",
    twitter: "@jonasletter",
    linkedin: null,
    notes: "Working on a revival of a forgotten 1930s Dutch newspaper face. Wants to trade licenses for an early look at the specimen. Has extremely strong opinions about hairline terminals.",
    followups: ["Swap license files before May 1"],
    meetings: [
      {
        id: "m-002-1",
        date: "2026-04-09",
        location: "TypeMedia studio visit · The Hague",
        notes: "Working on a revival of a forgotten 1930s Dutch newspaper face. Wants to trade licenses for an early look at the specimen. Has extremely strong opinions about hairline terminals.",
      },
    ],
  },
  {
    id: "p-003",
    name: "Priya Ramanathan",
    role: "Sound artist",
    company: "—",
    met: "Greenpoint open studios",
    metCity: "Brooklyn",
    captured: "2026-04-03",
    tags: ["to-enrich"],
    enriched: false,
    email: null,
    phone: null,
    web: null,
    twitter: null,
    linkedin: null,
    notes: "Makes field recordings of hydrophone data off the Konkan coast. Mentioned a new piece premiering at ISSUE Project Room in the fall. I have no contact info — find her via Aïda.",
    followups: ["Ask Aïda for an intro"],
    meetings: [
      {
        id: "m-003-1",
        date: "2026-04-03",
        location: "Greenpoint open studios · Brooklyn",
        notes: "Makes field recordings of hydrophone data off the Konkan coast. Mentioned a new piece premiering at ISSUE Project Room in the fall. I have no contact info — find her via Aïda.",
      },
    ],
  },
  {
    id: "p-004",
    name: "Teddy Okonkwo",
    role: "Independent curator",
    company: "Room Six",
    met: "Dinner at Marie's",
    metCity: "London",
    captured: "2026-03-28",
    tags: ["close"],
    enriched: true,
    email: "teddy@roomsix.uk",
    phone: "+44 7700 900 118",
    web: "roomsix.uk",
    twitter: null,
    linkedin: "in/teddyokonkwo",
    notes: "Will include three of my photographs in the late-summer group show if I can get vintage prints made in time. Promised to send measurements by the 24th. Does not drink coffee — bring sencha.",
    followups: ["Send measurements by the 24th", "Order vintage prints"],
    meetings: [
      {
        id: "m-004-1",
        date: "2026-03-28",
        location: "Dinner at Marie's · London",
        notes: "Will include three of my photographs in the late-summer group show if I can get vintage prints made in time. Promised to send measurements by the 24th. Does not drink coffee — bring sencha.",
      },
    ],
  },
  {
    id: "p-005",
    name: "Mei-Lin Chau",
    role: "Journalist",
    company: "The Baffler (contrib.)",
    met: "Cabinet launch party",
    metCity: "NYC",
    captured: "2026-03-21",
    tags: ["networking"],
    enriched: true,
    email: "mlc@meilinchau.work",
    phone: null,
    web: "meilinchau.work",
    twitter: "@meilin_chau",
    linkedin: null,
    notes: "Writing a long piece on artist-run residencies that quietly became real estate plays. Wants sources; I said I'd think about who to introduce her to without burning anyone.",
    followups: [],
    meetings: [
      {
        id: "m-005-1",
        date: "2026-03-21",
        location: "Cabinet launch party · NYC",
        notes: "Writing a long piece on artist-run residencies that quietly became real estate plays. Wants sources; I said I'd think about who to introduce her to without burning anyone.",
      },
    ],
  },
  {
    id: "p-006",
    name: "Rafael Ortiz",
    role: "Architect, editor",
    company: "Volume Quarterly",
    met: "Chinatown studio visit",
    metCity: "NYC",
    captured: "2026-03-17",
    tags: ["close"],
    enriched: true,
    email: "rafa@volumequarterly.org",
    phone: null,
    web: "volumequarterly.org",
    twitter: null,
    linkedin: null,
    notes: "Commissioning an essay from me for the 'Small Rooms' issue, 2000 words, kill fee 40%. Deadline is softer than it sounds. He'd rather I be late and honest than on-time and glib.",
    followups: ["First draft by May 15"],
    meetings: [
      {
        id: "m-006-1",
        date: "2026-03-17",
        location: "Chinatown studio visit · NYC",
        notes: "Commissioning an essay from me for the 'Small Rooms' issue, 2000 words, kill fee 40%. Deadline is softer than it sounds. He'd rather I be late and honest than on-time and glib.",
      },
    ],
  },
  {
    id: "p-007",
    name: "Sana Al-Mansouri",
    role: "Textile conservator",
    company: "V&A (freelance)",
    met: "Introduced by Teddy",
    metCity: "London",
    captured: "2026-03-11",
    tags: ["to-enrich"],
    enriched: false,
    email: "sana.almansouri@gmail.com",
    phone: null,
    web: null,
    twitter: null,
    linkedin: null,
    notes: "Conservator of 19th-century North African indigo dyes. Teddy says she once refused a Qatari museum commission on ethical grounds. Haven't met in person yet — just emails.",
    followups: ["Propose a coffee next time I'm in London"],
    meetings: [
      {
        id: "m-007-1",
        date: "2026-03-11",
        location: "Introduced by Teddy · London",
        notes: "Conservator of 19th-century North African indigo dyes. Teddy says she once refused a Qatari museum commission on ethical grounds. Haven't met in person yet — just emails.",
      },
    ],
  },
  {
    id: "p-008",
    name: "Cale Watanabe",
    role: "Bookseller",
    company: "Periphery Books",
    met: "Walk-in, bought a zine",
    metCity: "Oakland",
    captured: "2026-03-04",
    tags: ["networking"],
    enriched: true,
    email: "cale@peripherybooks.com",
    phone: null,
    web: "peripherybooks.com",
    twitter: null,
    linkedin: null,
    notes: "Stocks the kind of things that don't get stocked. Will take six copies of the new pamphlet on consignment. We disagreed, politely, about whether Didion belongs in the same case as Sontag.",
    followups: ["Ship 6 pamphlets to Oakland"],
    meetings: [
      {
        id: "m-008-1",
        date: "2026-03-04",
        location: "Walk-in, bought a zine · Oakland",
        notes: "Stocks the kind of things that don't get stocked. Will take six copies of the new pamphlet on consignment. We disagreed, politely, about whether Didion belongs in the same case as Sontag.",
      },
    ],
  },
  {
    id: "p-009",
    name: "Ingrid Haugen",
    role: "Printer, press operator",
    company: "Litli Press",
    met: "Reykjavík residency",
    metCity: "Reykjavík",
    captured: "2026-02-26",
    tags: ["close"],
    enriched: true,
    email: "ingrid@litli.is",
    phone: null,
    web: "litli.is",
    twitter: null,
    linkedin: null,
    notes: "Runs a one-woman risograph press out of a converted fish-processing plant. Offered me a two-week residency in January if I bring my own paper. She meant it.",
    followups: ["Confirm January dates", "Source 220gsm Munken"],
    meetings: [
      {
        id: "m-009-1",
        date: "2026-02-26",
        location: "Reykjavík residency · Reykjavík",
        notes: "Runs a one-woman risograph press out of a converted fish-processing plant. Offered me a two-week residency in January if I bring my own paper. She meant it.",
      },
    ],
  },
  {
    id: "p-010",
    name: "Hamid Karimi",
    role: "Filmmaker",
    company: "—",
    met: "Cabinet Magazine party",
    metCity: "NYC",
    captured: "2026-02-19",
    tags: ["to-enrich"],
    enriched: false,
    email: null,
    phone: null,
    web: null,
    twitter: null,
    linkedin: null,
    notes: "Short essayistic films. Cited Chris Marker and Kamran Shirdel in the same breath and meant both. Lost his card; I have only a first name and a face.",
    followups: ["Find him via Mei-Lin"],
    meetings: [
      {
        id: "m-010-1",
        date: "2026-02-19",
        location: "Cabinet Magazine party · NYC",
        notes: "Short essayistic films. Cited Chris Marker and Kamran Shirdel in the same breath and meant both. Lost his card; I have only a first name and a face.",
      },
    ],
  },
  {
    id: "p-011",
    name: "Beatrix Hollander",
    role: "Gallery director",
    company: "Hollander & Co.",
    met: "Art Basel preview",
    metCity: "Basel",
    captured: "2026-02-11",
    tags: ["networking"],
    enriched: true,
    email: "beatrix@hollanderco.ch",
    phone: "+41 79 000 00 00",
    web: "hollanderco.ch",
    twitter: null,
    linkedin: "in/beatrixhollander",
    notes: "Says the market is 'flat in an interesting way.' Would consider a solo show in the smaller room in '27. Not a promise. Still worth sending slides.",
    followups: ["Send slides — curated, not the full archive"],
    meetings: [
      {
        id: "m-011-1",
        date: "2026-02-11",
        location: "Art Basel preview · Basel",
        notes: "Says the market is 'flat in an interesting way.' Would consider a solo show in the smaller room in '27. Not a promise. Still worth sending slides.",
      },
    ],
  },
  {
    id: "p-012",
    name: "Yuki Tanaka",
    role: "Poet, translator",
    company: "—",
    met: "Reading at McNally",
    metCity: "NYC",
    captured: "2026-02-02",
    tags: ["close"],
    enriched: true,
    email: "yuki@twomoons.ink",
    phone: null,
    web: "twomoons.ink",
    twitter: null,
    linkedin: null,
    notes: "Translating Ryōkan into a kind of English nobody has tried before — no iambs, no capitals, lots of white space on the page. Offered to read drafts of my essay if I read her drafts.",
    followups: ["Exchange drafts in early May"],
    meetings: [
      {
        id: "m-012-1",
        date: "2026-02-02",
        location: "Reading at McNally · NYC",
        notes: "Translating Ryōkan into a kind of English nobody has tried before — no iambs, no capitals, lots of white space on the page. Offered to read drafts of my essay if I read her drafts.",
      },
    ],
  },
];
