import { Person } from "./types";

export const SEED_PEOPLE: Person[] = [
  {
    id: "p-001",
    name: "Mara Delacroix",
    role: "Photographer, curator",
    company: "Aperture Collective",
    location: "Printed Matter Art Book Fair",
    metCity: "NYC",
    captured: "2026-04-12",
    tags: ["close"],
    enriched: true,
    email: "mara@example.com",
    phone: null,
    web: "example.com",
    twitter: null,
    linkedin: "in/example",
    notes: "Talked for an hour about why print culture archives keep getting digitized and then abandoned. Invited me to the next residency; I said yes before checking the calendar.",
    followups: ["Send the magazine scan", "Intro to someone re: residency slot"],
    meetings: [
      {
        id: "m-001-1",
        date: "2026-04-12",
        location: "Printed Matter Art Book Fair · NYC",
        notes: "Talked for an hour about why print culture archives keep getting digitized and then abandoned. Invited me to the next residency; I said yes before checking the calendar.",
      },
    ],
  },
  {
    id: "p-002",
    name: "Erik Solberg",
    role: "Type designer",
    company: "Letter Foundry",
    location: "TypeMedia studio visit",
    metCity: "The Hague",
    captured: "2026-04-09",
    tags: ["networking"],
    enriched: true,
    email: "erik@example.com",
    phone: null,
    web: "example.com",
    twitter: "@example",
    linkedin: null,
    notes: "Working on a revival of a forgotten 1930s newspaper face. Wants to trade licenses for an early look at the specimen. Has strong opinions about hairline terminals.",
    followups: ["Swap license files before May 1"],
    meetings: [
      {
        id: "m-002-1",
        date: "2026-04-09",
        location: "TypeMedia studio visit · The Hague",
        notes: "Working on a revival of a forgotten 1930s newspaper face. Wants to trade licenses for an early look at the specimen. Has strong opinions about hairline terminals.",
      },
    ],
  },
  {
    id: "p-003",
    name: "Priya Nair",
    role: "Sound artist",
    company: "—",
    location: "Greenpoint open studios",
    metCity: "Brooklyn",
    captured: "2026-04-03",
    tags: ["to-enrich"],
    enriched: false,
    email: null,
    phone: null,
    web: null,
    twitter: null,
    linkedin: null,
    notes: "Makes field recordings of hydrophone data off the coast. Mentioned a new piece premiering in the fall. No contact info yet — find her through Mara.",
    followups: ["Ask Mara for an intro"],
    meetings: [
      {
        id: "m-003-1",
        date: "2026-04-03",
        location: "Greenpoint open studios · Brooklyn",
        notes: "Makes field recordings of hydrophone data off the coast. Mentioned a new piece premiering in the fall. No contact info yet — find her through Mara.",
      },
    ],
  },
  {
    id: "p-004",
    name: "Tobias Mensah",
    role: "Independent curator",
    company: "Room Six",
    location: "Dinner at a friend's",
    metCity: "London",
    captured: "2026-03-28",
    tags: ["close"],
    enriched: true,
    email: "tobias@example.com",
    phone: "+44 7700 900 000",
    web: "example.com",
    twitter: null,
    linkedin: "in/example",
    notes: "Will include three of my photographs in the late-summer group show if I can get vintage prints made in time. Promised to send measurements by the 24th. Does not drink coffee.",
    followups: ["Send measurements by the 24th", "Order vintage prints"],
    meetings: [
      {
        id: "m-004-1",
        date: "2026-03-28",
        location: "Dinner at a friend's · London",
        notes: "Will include three of my photographs in the late-summer group show if I can get vintage prints made in time. Promised to send measurements by the 24th. Does not drink coffee.",
      },
    ],
  },
  {
    id: "p-005",
    name: "Lin Beaumont",
    role: "Journalist",
    company: "The Baffler (contrib.)",
    location: "Cabinet launch party",
    metCity: "NYC",
    captured: "2026-03-21",
    tags: ["networking"],
    enriched: true,
    email: "lin@example.com",
    phone: null,
    web: "example.com",
    twitter: "@example",
    linkedin: null,
    notes: "Writing a long piece on artist-run residencies that quietly became real estate plays. Wants sources; I said I'd think about who to introduce her to without burning anyone.",
    followups: [],
    meetings: [
      {
        id: "m-005-1",
        date: "2026-03-21",
        location: "Cabinet launch party · NYC",
        notes: "Writing a long piece on artist-run residencies that quietly became real estate plays. Wants sources; I said I'd think about who to introduce her to without burning anyone.",
      },
    ],
  },
  {
    id: "p-006",
    name: "Rafael Voss",
    role: "Architect, editor",
    company: "Volume Quarterly",
    location: "Chinatown studio visit",
    metCity: "NYC",
    captured: "2026-03-17",
    tags: ["close"],
    enriched: true,
    email: "rafael@example.com",
    phone: null,
    web: "example.com",
    twitter: null,
    linkedin: null,
    notes: "Commissioning an essay for the 'Small Rooms' issue, 2000 words, kill fee 40%. Deadline is softer than it sounds. He'd rather I be late and honest than on-time and glib.",
    followups: ["First draft by May 15"],
    meetings: [
      {
        id: "m-006-1",
        date: "2026-03-17",
        location: "Chinatown studio visit · NYC",
        notes: "Commissioning an essay for the 'Small Rooms' issue, 2000 words, kill fee 40%. Deadline is softer than it sounds. He'd rather I be late and honest than on-time and glib.",
      },
    ],
  },
  {
    id: "p-007",
    name: "Sana Khalil",
    role: "Textile conservator",
    company: "V&A (freelance)",
    location: "Introduced by Tobias",
    metCity: "London",
    captured: "2026-03-11",
    tags: ["to-enrich"],
    enriched: false,
    email: "sana@example.com",
    phone: null,
    web: null,
    twitter: null,
    linkedin: null,
    notes: "Conservator specializing in 19th-century indigo dyes. Tobias says she once refused a major museum commission on ethical grounds. Haven't met in person yet — just emails.",
    followups: ["Propose a coffee next time I'm in London"],
    meetings: [
      {
        id: "m-007-1",
        date: "2026-03-11",
        location: "Introduced by Tobias · London",
        notes: "Conservator specializing in 19th-century indigo dyes. Tobias says she once refused a major museum commission on ethical grounds. Haven't met in person yet — just emails.",
      },
    ],
  },
  {
    id: "p-008",
    name: "Cal Watanabe",
    role: "Bookseller",
    company: "Periphery Books",
    location: "Walk-in, bought a zine",
    metCity: "Oakland",
    captured: "2026-03-04",
    tags: ["networking"],
    enriched: true,
    email: "cal@example.com",
    phone: null,
    web: "example.com",
    twitter: null,
    linkedin: null,
    notes: "Stocks the kind of things that don't get stocked. Will take six copies of the new pamphlet on consignment. We disagreed, politely, about whether Didion belongs in the same case as Sontag.",
    followups: ["Ship 6 pamphlets to Oakland"],
    meetings: [
      {
        id: "m-008-1",
        date: "2026-03-04",
        location: "Walk-in, bought a zine · Oakland",
        notes: "Stocks the kind of things that don't get stocked. Will take six copies of the new pamphlet on consignment. We disagreed, politely, about whether Didion belongs in the same case as Sontag.",
      },
    ],
  },
  {
    id: "p-009",
    name: "Ingrid Haas",
    role: "Printer, press operator",
    company: "Litli Press",
    location: "Reykjavík residency",
    metCity: "Reykjavík",
    captured: "2026-02-26",
    tags: ["close"],
    enriched: true,
    email: "ingrid@example.com",
    phone: null,
    web: "example.com",
    twitter: null,
    linkedin: null,
    notes: "Runs a one-woman risograph press out of a converted fish-processing plant. Offered me a two-week residency in January if I bring my own paper. She meant it.",
    followups: ["Confirm January dates", "Source 220gsm Munken"],
    meetings: [
      {
        id: "m-009-1",
        date: "2026-02-26",
        location: "Reykjavík residency · Reykjavík",
        notes: "Runs a one-woman risograph press out of a converted fish-processing plant. Offered me a two-week residency in January if I bring my own paper. She meant it.",
      },
    ],
  },
  {
    id: "p-010",
    name: "Hamid Reza",
    role: "Filmmaker",
    company: "—",
    location: "Cabinet Magazine party",
    metCity: "NYC",
    captured: "2026-02-19",
    tags: ["to-enrich"],
    enriched: false,
    email: null,
    phone: null,
    web: null,
    twitter: null,
    linkedin: null,
    notes: "Short essayistic films. Cited Chris Marker and a lesser-known Iranian director in the same breath and meant both. Lost his card; I have only a first name and a face.",
    followups: ["Find him via Lin"],
    meetings: [
      {
        id: "m-010-1",
        date: "2026-02-19",
        location: "Cabinet Magazine party · NYC",
        notes: "Short essayistic films. Cited Chris Marker and a lesser-known Iranian director in the same breath and meant both. Lost his card; I have only a first name and a face.",
      },
    ],
  },
  {
    id: "p-011",
    name: "Beatrix Lange",
    role: "Gallery director",
    company: "Lange & Co.",
    location: "Art Basel preview",
    metCity: "Basel",
    captured: "2026-02-11",
    tags: ["networking"],
    enriched: true,
    email: "beatrix@example.com",
    phone: "+41 79 000 00 00",
    web: "example.com",
    twitter: null,
    linkedin: "in/example",
    notes: "Says the market is 'flat in an interesting way.' Would consider a solo show in the smaller room in '27. Not a promise. Still worth sending slides.",
    followups: ["Send slides — curated, not the full archive"],
    meetings: [
      {
        id: "m-011-1",
        date: "2026-02-11",
        location: "Art Basel preview · Basel",
        notes: "Says the market is 'flat in an interesting way.' Would consider a solo show in the smaller room in '27. Not a promise. Still worth sending slides.",
      },
    ],
  },
  {
    id: "p-012",
    name: "Yuki Mori",
    role: "Poet, translator",
    company: "—",
    location: "Reading at McNally",
    metCity: "NYC",
    captured: "2026-02-02",
    tags: ["close"],
    enriched: true,
    email: "yuki@example.com",
    phone: null,
    web: "example.com",
    twitter: null,
    linkedin: null,
    notes: "Translating classical Japanese poetry into a kind of English nobody has tried before — no iambs, no capitals, lots of white space on the page. Offered to read drafts of my essay if I read her drafts.",
    followups: ["Exchange drafts in early May"],
    meetings: [
      {
        id: "m-012-1",
        date: "2026-02-02",
        location: "Reading at McNally · NYC",
        notes: "Translating classical Japanese poetry into a kind of English nobody has tried before — no iambs, no capitals, lots of white space on the page. Offered to read drafts of my essay if I read her drafts.",
      },
    ],
  },
];
